version: "3.9"

services:
  crud:
    image: postgres
    container_name: database_artcomic
    restart: always
    ports:
      - 5777:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
